swagger: '2.0'
info:
  version: '1.0'
  title: "examjan"
  description: Gioco guardi e ladri
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: examjan.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /games:
    x-summary: Games Collection
    get:
      summary: List All Games
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
          examples:
            application/json:
              - guardia: -5
                ladro: 5
                id: 550e8400-e29b-41d4-a716-446655440000
                catturato: false
              - guardia: 8
                ladro: 8
                id: 84817c20-14e0-11e9-ab14-d663bd873d93
                catturato: true
        404:
          description: Non sono presenti partite
  /games/gameId:
    x-summary: A single game
    get:
      summary: Return a game
      responses:
        200:
          description: Succesful response
          schema:
            $ref: '#/definitions/Game'
          examples:
            application/json:
              guardia: -5
              ladro: 5
              id: 550e8400-e29b-41d4-a716-446655440000
              Complcatturato: false
        404:
          description: La partita non esiste
definitions:
  Game:
    title: Game
    type: object
    properties:
      guardia:
        type: integer
      ladro:
        type: integer
      id:
        type: string
      catturato:
        type: boolean